name: MyRixi API Docker CI/CD

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'MyRixi-API/**'
      - '.github/workflows/myrixi-api-docker-workflow.yml'
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - 'MyRixi-API/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Important pour pouvoir pousser vers GHCR
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore dependencies
        run: dotnet restore MyRixi-API/MyRixi-API.csproj
        
      - name: Build and test
        run: |
          dotnet build MyRixi-API/MyRixi-API.csproj --configuration Release
          dotnet test MyRixi-API/MyRixi-API.csproj --no-build --verbosity normal
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/myrixi-api
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,format=short
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./MyRixi-API/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
  deploy-to-coolify:
    needs: build-and-push
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify deployment
        run: |
          curl -X POST ${{ secrets.COOLIFY_WEBHOOK_URL }} \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_API_TOKEN }}" \
            -d '{
              "repository": "MyRixi",
              "branch": "${{ github.ref_name }}",
              "image": "ghcr.io/${{ github.repository_owner }}/myrixi-api:sha-${{ github.sha }}"
            }'
